package com.ubaid.app.model;

public enum Table
{
	Event,
	EventPart,
	EventTemplate,
	EventTypeUsage,
	EventPartDefaultUsage,
	EVentType,
	EventStatus,
	ProviderEventRelation,
	Sport,
	Provider,
	EventParticipantRelation,
	EventParticipantRestriction,
	Location,
	LocationType,
	LocationRelation,
	LocationRelationType,
	BettingOffer,
	BettingOfferStatus,
	BettingType,
	BettingTypeUsage,
	Outcome,
	OUtcomeStatus,
	OutcomeType,
	OutcomeTypeUsage,
	OutcomeTypeBettingTypeRelation,
	Participant,
	ParticipantUsage,
	ParticipantRole,
	ParticipantTypeRoleUsage,
	ParticipantType,
	ParticipantRelation,
	ParticipantRelationType,
	Source,
	OddsHistory
	
}
